# Generated by Django 5.0.7 on 2025-02-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bems_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shift',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
