# Generated by Django 5.0.7 on 2025-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('pick_up', 'Pick Up'), ('flt_sqwk', 'Flight Squawk'), ('cro', 'CRO'), ('troubleshooting', 'Troubleshooting'), ('software', 'Software'), ('other', 'Other')], max_length=50),
        ),
    ]
