# Generated by Django 5.0.7 on 2025-02-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
        ('work', '0005_airplane_delivered_airplane_ticketed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplane.airplane'),
        ),
        migrations.DeleteModel(
            name='Airplane',
        ),
    ]
