# Generated by Django 5.0.7 on 2025-02-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_work_airplane_delete_airplane'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
