# Generated by Django 5.0.7 on 2025-02-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(unique=True)),
                ('effectivity', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('ticketed', models.BooleanField(default=False)),
            ],
        ),
    ]
