# Generated by Django 5.0.7 on 2025-02-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='effectivity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='line_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
