# Generated by Django 5.0.7 on 2025-02-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0002_alter_airplane_effectivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
